// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: t.flex

import java.util.*;


@SuppressWarnings("fallthrough")
public class AnalisadoLexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\2\2\1\3\24\0\1\4\5\0\1\5"+
    "\1\6\4\0\1\7\1\0\12\10\2\0\1\11\1\12"+
    "\1\13\2\0\16\14\1\15\13\14\1\16\1\0\1\17"+
    "\1\0\1\20\1\0\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\2\22\1\32\1\33\1\34"+
    "\1\35\2\22\1\36\1\37\1\40\1\41\1\42\1\22"+
    "\1\43\1\44\1\22\12\0\1\2\u01a2\0\2\2\326\0"+
    "\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\15\1\1\10\1\11\1\12\15\13\1\14\3\13"+
    "\1\12\1\0\1\13\1\15\1\16\4\13\1\0\1\17"+
    "\1\20\1\21\4\13\1\22\1\23\1\0\2\13\1\0"+
    "\1\13\1\0\1\24\1\25\1\26\1\13\1\22\1\23"+
    "\2\13\1\27\1\13\4\0\1\30\1\23\1\0\1\13"+
    "\1\0\1\27\2\0\1\13\1\0\1\31\2\0\1\32"+
    "\1\0\2\27\1\0\1\13\4\0\1\33\2\27\1\0"+
    "\1\31\4\0\1\34\10\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\45\0\112\0\45\0\45\0\157\0\224"+
    "\0\271\0\336\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc"+
    "\0\u01e1\0\u0206\0\u022b\0\u0250\0\u0275\0\u029a\0\45\0\45"+
    "\0\u02bf\0\u02e4\0\u0128\0\u0309\0\u032e\0\u0353\0\u0378\0\u039d"+
    "\0\u03c2\0\u03e7\0\u040c\0\u0431\0\u0456\0\u047b\0\u0128\0\u04a0"+
    "\0\u04c5\0\u04ea\0\u050f\0\u0534\0\u0559\0\u0128\0\u0128\0\u057e"+
    "\0\u05a3\0\u05c8\0\u05ed\0\u0612\0\u0128\0\u0128\0\u0128\0\u0637"+
    "\0\u065c\0\u0681\0\u06a6\0\u06cb\0\u06f0\0\u0715\0\u073a\0\u075f"+
    "\0\u0784\0\u07a9\0\u07ce\0\u0128\0\u0128\0\u0128\0\u07f3\0\u0818"+
    "\0\u083d\0\u0862\0\u0887\0\u08ac\0\u08d1\0\u08f6\0\u091b\0\u0940"+
    "\0\u0965\0\u0128\0\u098a\0\u09af\0\u09d4\0\u09f9\0\u0a1e\0\u0a43"+
    "\0\u0a68\0\u0a8d\0\u0ab2\0\u0ab2\0\u0ad7\0\u0afc\0\u0128\0\u0b21"+
    "\0\u0b46\0\u0b6b\0\u0b90\0\u0bb5\0\u0bda\0\u0bff\0\u0c24\0\u0c49"+
    "\0\45\0\u0c6e\0\u0c93\0\u0cb8\0\45\0\u0cdd\0\u0d02\0\u0d27"+
    "\0\u0d4c\0\45\0\u0d71\0\u0d96\0\u0dbb\0\u0de0\0\u0e05\0\u0e2a"+
    "\0\u0e4f\0\u0e74";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\2\1\5\1\6\1\2\1\7"+
    "\1\10\1\2\1\11\2\12\3\2\1\13\3\14\1\15"+
    "\1\16\1\14\1\17\1\20\1\14\1\21\1\22\1\23"+
    "\1\14\1\24\1\25\1\14\1\26\2\14\46\0\1\2"+
    "\53\0\1\7\46\0\1\27\44\0\1\30\53\0\24\31"+
    "\20\0\1\32\11\33\1\34\1\33\1\35\10\33\20\0"+
    "\1\32\24\33\20\0\1\32\22\33\1\36\1\33\20\0"+
    "\1\32\11\33\1\37\12\33\20\0\1\32\1\40\23\33"+
    "\20\0\1\32\13\33\1\41\2\33\1\42\5\33\20\0"+
    "\1\32\1\43\7\33\1\44\13\33\20\0\1\32\14\33"+
    "\1\45\7\33\20\0\1\32\13\33\1\46\1\33\1\47"+
    "\6\33\20\0\1\32\14\33\1\50\7\33\20\0\1\32"+
    "\7\33\1\51\14\33\20\0\1\32\1\52\23\33\10\0"+
    "\1\53\3\0\2\54\2\0\1\55\24\31\10\0\1\32"+
    "\7\0\25\32\20\0\1\32\11\33\1\56\12\33\20\0"+
    "\1\32\3\33\1\57\20\33\20\0\1\32\1\60\23\33"+
    "\20\0\1\32\14\33\1\61\7\33\20\0\1\32\16\33"+
    "\1\62\5\33\20\0\1\32\17\33\1\63\4\33\14\0"+
    "\2\64\2\0\1\32\24\33\20\0\1\32\22\33\1\65"+
    "\1\33\20\0\1\32\13\33\1\66\10\33\20\0\1\32"+
    "\17\33\1\67\4\33\20\0\1\32\11\33\1\70\12\33"+
    "\20\0\1\32\12\33\1\71\11\33\20\0\1\32\1\72"+
    "\23\33\20\0\1\32\11\33\1\73\12\33\10\0\1\53"+
    "\3\0\2\54\2\0\1\55\45\0\24\74\10\0\1\75"+
    "\3\0\2\76\2\0\25\32\20\0\1\32\2\33\1\77"+
    "\21\33\20\0\1\32\1\100\23\33\14\0\2\101\2\0"+
    "\1\32\24\33\20\0\1\32\4\33\1\102\17\33\21\0"+
    "\24\103\20\0\1\32\23\33\1\104\20\0\1\32\4\33"+
    "\1\105\17\33\20\0\1\32\17\33\1\106\4\33\20\0"+
    "\1\32\20\33\1\107\3\33\10\0\1\110\3\0\2\54"+
    "\3\0\24\74\10\0\1\75\7\0\1\55\24\32\21\0"+
    "\24\111\20\0\1\32\17\33\1\112\4\33\20\0\1\32"+
    "\17\33\1\113\4\33\21\0\24\114\20\0\1\32\6\33"+
    "\1\115\15\33\10\0\1\116\3\0\1\117\1\120\2\0"+
    "\1\121\24\103\20\0\1\32\4\33\1\122\17\33\10\0"+
    "\1\110\3\0\2\54\37\0\1\123\7\0\1\124\24\111"+
    "\20\0\1\32\11\33\1\125\12\33\16\0\1\126\1\0"+
    "\1\32\24\33\10\0\1\127\3\0\2\130\2\0\1\131"+
    "\24\114\20\0\1\32\4\33\1\132\17\33\10\0\1\116"+
    "\3\0\1\117\1\120\2\0\1\121\45\0\24\133\21\0"+
    "\5\133\1\134\16\133\10\0\1\135\3\0\2\136\37\0"+
    "\1\123\7\0\1\124\34\0\1\123\3\0\2\76\47\0"+
    "\1\32\23\33\1\137\11\0\1\140\1\0\1\140\41\0"+
    "\1\127\3\0\2\130\2\0\1\131\45\0\24\141\10\0"+
    "\1\142\3\0\2\143\47\0\1\32\15\33\1\144\6\33"+
    "\10\0\1\145\3\0\1\117\1\120\3\0\24\133\10\0"+
    "\1\135\4\0\1\146\2\0\1\121\45\0\24\147\12\0"+
    "\1\150\4\0\1\151\35\0\1\152\3\0\2\130\3\0"+
    "\24\141\10\0\1\142\7\0\1\131\45\0\24\153\16\0"+
    "\1\154\1\0\1\32\24\33\10\0\1\145\3\0\1\117"+
    "\1\120\55\0\1\155\26\0\1\135\4\0\1\146\2\0"+
    "\1\121\24\147\4\0\1\156\50\0\1\152\3\0\2\130"+
    "\37\0\1\142\7\0\1\131\24\153\11\0\1\157\1\0"+
    "\1\157\41\0\1\160\46\0\1\161\4\0\1\162\31\0"+
    "\1\163\2\0\1\164\1\160\40\0\1\165\57\0\1\151"+
    "\35\0\1\166\44\0\1\167\40\0\1\163\3\0\1\166"+
    "\40\0\1\170\2\0\1\171\1\167\53\0\1\162\35\0"+
    "\1\172\40\0\1\170\3\0\1\172\34\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3737];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\2\11\20\1\2\11\23\1\1\0"+
    "\7\1\1\0\11\1\1\0\2\1\1\0\1\1\1\0"+
    "\12\1\4\0\2\1\1\0\1\1\1\0\1\1\2\0"+
    "\1\1\1\0\1\1\2\0\1\1\1\0\2\1\1\0"+
    "\1\1\4\0\1\11\2\1\1\0\1\11\4\0\1\11"+
    "\10\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    static Scanner scanner = new Scanner(System.in);

    static int some = 0;
    static int all = 0;
    static int erros = 0;
    static int only = 0;
    static int value = 0;
    static int min = 0;
    static int max = 0;
    static int exactly = 0;
    static int that = 0;
    static int not = 0;
    static int and = 0;
    static int or = 0;
    static int fecha_par = 0;
    static int abre_par = 0;
    static int maior = 0;
    static int menor = 0;
    static int num = 0;
    static int maior_ou_igual= 0;
    static int menor_ou_igual = 0;
    static int propriedade_has = 0;
    static int propriedade_is = 0;
    static int propriedade = 0;
    static int classe = 0;
    static int classeComposta = 0;
    static int classeUnderline = 0;
    static int valor_int = 0;
    static int valor_float = 0;

    public static class Compiler {
  
    //exibe a quantidade de tokens 
    public static void qnt_tokens(){
        System.out.println("\n--------------------------------------------");
        System.out.println("        TOKEN        |      QUANTIDADE      ");
        System.out.println("--------------------------------------------");

        if(some > 0){
            System.out.println("        SOME         |           " + some);
            System.out.println("--------------------------------------------");
        }
        if(only > 0){
            System.out.println("        ONLY         |           " + only);
            System.out.println("--------------------------------------------");
        }
        if(all > 0){
            System.out.println("         ALL         |           " + all);
            System.out.println("--------------------------------------------");
        }
        if(value > 0){
            System.out.println("        VALUE        |           " + value);
            System.out.println("--------------------------------------------");
        }
        if(min > 0){
            System.out.println("         MIN         |           " + min);
            System.out.println("--------------------------------------------");
        }
        if(max > 0){
            System.out.println("         MAX         |           " + max);
            System.out.println("--------------------------------------------");
        }
        if(exactly > 0){
            System.out.println("       EXACTLY       |           " + exactly);
            System.out.println("--------------------------------------------");
        }
        if(that > 0){
            System.out.println("        THAT         |           " + that);
            System.out.println("--------------------------------------------");
        }
        if(not > 0){
            System.out.println("         NOT         |           " + not);
            System.out.println("--------------------------------------------");
        }
        if(and > 0){
            System.out.println("         AND         |           " + and);
            System.out.println("--------------------------------------------");
        }
        if(or > 0){
            System.out.println("         OR          |           " + or);
            System.out.println("--------------------------------------------");
        }
        if(abre_par > 0){
            System.out.println("          (          |           " + abre_par);
            System.out.println("--------------------------------------------");
        }
        if(fecha_par > 0){
            System.out.println("          )          |           " + fecha_par);
            System.out.println("--------------------------------------------");
        }
        if(maior > 0){
            System.out.println("          >          |           " + maior);
            System.out.println("--------------------------------------------");
        }
        if(menor > 0){
            System.out.println("          <          |           " + menor);
            System.out.println("--------------------------------------------");
        }
        if(maior_ou_igual > 0){
            System.out.println("         >=          |           " + maior_ou_igual);
            System.out.println("--------------------------------------------");
        }
        if(menor_ou_igual > 0){
            System.out.println("         <=          |           " + menor_ou_igual);
            System.out.println("--------------------------------------------");
        }
        if(num > 0){
            System.out.println("       NÚMERO        |           " + num);
            System.out.println("--------------------------------------------");
        }
        if(propriedade_has > 0){
            System.out.println("  PROPRIEDADE (HAS)  |           " + propriedade_has);
            System.out.println("--------------------------------------------");
        }
        if(propriedade_is > 0){
            System.out.println("  PROPRIEDADE (IS)   |           " + propriedade_is);
            System.out.println("--------------------------------------------");
        }
        if(classe > 0){
            System.out.println("       Classe        |           " + classe);
            System.out.println("--------------------------------------------");
        }
        if(classeComposta > 0){
            System.out.println("   Classe Composta   |           " + classeComposta);
            System.out.println("--------------------------------------------");
        }
         if(classeUnderline > 0){
            System.out.println("  Classe Underline   |           " + classeUnderline);
            System.out.println("--------------------------------------------");
        }
        if(propriedade > 0){
            System.out.println("  Propriedades Total |           " + propriedade);
            System.out.println("--------------------------------------------");
        }
        if(valor_int > 0){
            System.out.println(" Valor para INTEGER  |           " + valor_int);
            System.out.println("--------------------------------------------");
        }
        if(valor_float > 0){
            System.out.println("  Valor para FLOAT   |           " + valor_float);
            System.out.println("--------------------------------------------");
        }
        if(erros > 0){
            System.out.println("     >> ERROS        |           " + erros);
            System.out.println("--------------------------------------------");
        }
    }
}
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalisadoLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
          // fall through
          case 29: break;
          case 2:
            { System.out.print(yytext());
            }
          // fall through
          case 30: break;
          case 3:
            { System.out.println("> Encontrei um Abre parentese"); abre_par++;
            }
          // fall through
          case 31: break;
          case 4:
            { System.out.println("> Encontrei um Fecha parentese");fecha_par++;
            }
          // fall through
          case 32: break;
          case 5:
            { System.out.println("> Encontrei um Número {" + yytext() + "}"); num++;
            }
          // fall through
          case 33: break;
          case 6:
            { System.out.println("> Encontrei um Menor que");menor++;
            }
          // fall through
          case 34: break;
          case 7:
            { System.out.println("> Encontrei um Maior que");maior++;
            }
          // fall through
          case 35: break;
          case 8:
            { System.out.println("> Encontrei um Menor ou igual");menor_ou_igual++;
            }
          // fall through
          case 36: break;
          case 9:
            { System.out.println("> Encontrei um Maior ou igual");maior_ou_igual++;
            }
          // fall through
          case 37: break;
          case 10:
            { System.out.println("> Encontrei uma Classe {" + yytext() + "}"); classe++;
            }
          // fall through
          case 38: break;
          case 11:
            { System.out.println("> Encontrei um ERRO {" + yytext() + "}");erros++;
            }
          // fall through
          case 39: break;
          case 12:
            { System.out.println("> Encontrei a palavra reservada OR");or++;
            }
          // fall through
          case 40: break;
          case 13:
            { System.out.println("> Encontrei a palavra reservada ALL");all++;
            }
          // fall through
          case 41: break;
          case 14:
            { System.out.println("> Encontrei a palavra reservada AND");and++;
            }
          // fall through
          case 42: break;
          case 15:
            { System.out.println("> Encontrei a palavra reservada MAX");max++;
            }
          // fall through
          case 43: break;
          case 16:
            { System.out.println("> Encontrei a palavra reservada MIN");min++;
            }
          // fall through
          case 44: break;
          case 17:
            { System.out.println("> Encontrei a palavra reservada NOT");not++;
            }
          // fall through
          case 45: break;
          case 18:
            { System.out.println("> Encontrei uma Classe Composta {" + yytext() + "}");classeComposta++;
            }
          // fall through
          case 46: break;
          case 19:
            { System.out.println("> Encontrei uma Classe_Underline {" + yytext() + "}"); classeUnderline++;
            }
          // fall through
          case 47: break;
          case 20:
            { System.out.println("> Encontrei a palavra reservada ONLY");only++;
            }
          // fall through
          case 48: break;
          case 21:
            { System.out.println("> Encontrei a palavra reservada SOME");some++;
            }
          // fall through
          case 49: break;
          case 22:
            { System.out.println("> Encontrei a palavra reservada THAT");that++;
            }
          // fall through
          case 50: break;
          case 23:
            { System.out.println("> Encontrei uma propriedade has {" + yytext() + "}");propriedade++;propriedade_has++;
            }
          // fall through
          case 51: break;
          case 24:
            { System.out.println("> Encontrei a palavra reservada VALUE");value++;
            }
          // fall through
          case 52: break;
          case 25:
            { System.out.println("> Encontrei uma propriedade is {" + yytext() + "}");propriedade++;propriedade_is++;
            }
          // fall through
          case 53: break;
          case 26:
            { System.out.println("> Encontrei a palavra reservada EXACTLY");exactly++;
            }
          // fall through
          case 54: break;
          case 27:
            { System.out.println("> Encontrei uma condição: {" + yytext() + "}");valor_float++;
            }
          // fall through
          case 55: break;
          case 28:
            { System.out.println("> Encontrei uma condição: {" + yytext() + "}");valor_int++;
            }
          // fall through
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnalisadoLexico [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        AnalisadoLexico scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new AnalisadoLexico(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
