
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 10;
  public static final int IS = 25;
  public static final int MENOR = 14;
  public static final int INT = 29;
  public static final int OR = 11;
  public static final int HAS = 24;
  public static final int ALL = 3;
  public static final int ABREPAR = 17;
  public static final int NOVALINHA = 22;
  public static final int NOT = 9;
  public static final int VALUE = 4;
  public static final int CLASSEUNDER = 28;
  public static final int VIRGULA = 21;
  public static final int MENORIG = 16;
  public static final int FLOAT = 30;
  public static final int ABRECHAVE = 19;
  public static final int EOF = 0;
  public static final int THAT = 8;
  public static final int NUMERO = 23;
  public static final int error = 1;
  public static final int MAIOR = 13;
  public static final int FECHACHAVE = 20;
  public static final int FECHAPAR = 18;
  public static final int MIN = 5;
  public static final int EXACTLY = 7;
  public static final int SOME = 2;
  public static final int CLASSE = 26;
  public static final int MAIORIG = 15;
  public static final int MAX = 6;
  public static final int CLASSECOMP = 27;
  public static final int ONLY = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SOME",
  "ALL",
  "VALUE",
  "MIN",
  "MAX",
  "EXACTLY",
  "THAT",
  "NOT",
  "AND",
  "OR",
  "ONLY",
  "MAIOR",
  "MENOR",
  "MAIORIG",
  "MENORIG",
  "ABREPAR",
  "FECHAPAR",
  "ABRECHAVE",
  "FECHACHAVE",
  "VIRGULA",
  "NOVALINHA",
  "NUMERO",
  "HAS",
  "IS",
  "CLASSE",
  "CLASSECOMP",
  "CLASSEUNDER",
  "INT",
  "FLOAT"
  };
}

